# Generated by Django 5.1.2 on 2024-11-10 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='ratings',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ratings',
        ),
    ]
